platform: linux
image_resource:
  type: docker-image
  source:
    repository: riffci/fats

inputs:
- name: git-pfs-ci
- name: git-faas-acceptance-test-suite
- name: git-riff
- name: cli-version
- name: cli-binary
- name: gcs-riff-chart-latest-version
- name: gcs-riff-chart-latest-name
- name: java-function-invoker-version
- name: node-function-invoker-version
- name: python2-function-invoker-version
- name: shell-function-invoker-version

run:
  path: git-pfs-ci/tasks/acceptance-tests/run

params:
  GINKGO_FOCUS: SampleFunctionTest
  KUBECONFIG_STRING: replace-me
  KUBECONFIG_CERT: replace-me
  KUBECONFIG_KEY: replace-me
  DOCKER_TEST_ORG: replace-me
  DOCKER_USERNAME: replace-me
  DOCKER_PASSWORD: replace-me
