<%
  K8sEnvironment=Struct.new(
    :name,
    :lpass_name
  )

  RiffComponent=Struct.new(
  :name,
  :docker_image_name,
  :git_org_name,
  :git_repo_name,
  :build_task_file)

  riff_components = [
    RiffComponent.new('function-sidecar',     'function-sidecar',     'projectriff', 'function-sidecar',      'sidecar/build/task.yml'),
    RiffComponent.new('http-gateway',         'http-gateway',         'projectriff', 'http-gateway',          'http-gateway/build/task.yml'),
    RiffComponent.new('topic-controller',     'topic-controller',     'projectriff', 'topic-controller',      'topic-controller/build/task.yml'),
    RiffComponent.new('function-controller',  'function-controller',  'projectriff', 'function-controller',   'function-controller/build/task.yml'),

    RiffComponent.new(  'node-function-invoker',
                        'node-function-invoker',
                        'projectriff',
                        'node-function-invoker',
                        'node-invoker/build/task.yml'),

    RiffComponent.new(  'shell-function-invoker',
                        'shell-function-invoker',
                        'projectriff',
                        'shell-function-invoker',
                        'shell-invoker/build/task.yml'),

    RiffComponent.new(  'java-function-invoker',
                        'java-function-invoker',
                        'projectriff',
                        'java-function-invoker',
                        'java-invoker/build/task.yml'),

    RiffComponent.new(  'python2-function-invoker',
                        'python2-function-invoker',
                        'projectriff',
                        'python2-function-invoker',
                        'python2-invoker/build/task.yml'),
  ]

  charts_bucket_name='riff-charts'

  k8s_envs = [
    K8sEnvironment.new('gke', 'pfs-gcp-kubeconfig-gke-ci'),
  ]

slack_notification="""
  on_failure:
    do:
    - put: slack-alert
      params:
        channel: '#pfs-ops'
        text: |
          $BUILD_PIPELINE_NAME : $BUILD_JOB_NAME Failed
          https://ci.projectriff.io/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME
"""

%>

resource_types:
- name: slack-notification
  type: docker-image
  source:
    repository: cfcommunity/slack-notification-resource
    tag: latest

- name: gcs-resource
  type: docker-image
  source:
    repository: frodenas/gcs-resource

- name: github-status
  type: docker-image
  source:
    repository: dpb587/github-status-resource
    tag: master

resources:

- name: gcs-riff-charts
  type: gcs-resource
  source:
    bucket: <%= charts_bucket_name %>
    json_key: ((gcp-json-key))
    regexp: riff*tgz

- name: gcs-riff-chart-index
  type: gcs-resource
  source:
    bucket: <%= charts_bucket_name %>
    json_key: ((gcp-json-key))
    versioned_file: index.yaml

- name: gcs-riff-chart-latest-version
  type: gcs-resource
  source:
    bucket: <%= charts_bucket_name %>
    json_key: ((gcp-json-key))
    versioned_file: latest_version

- name: gcs-riff-chart-latest-name
  type: gcs-resource
  source:
    bucket: <%= charts_bucket_name %>
    json_key: ((gcp-json-key))
    versioned_file: latest_name

<% riff_components.each do |component| %>
- name: <%= component.name %>-version
  type: semver
  source:
    driver: gcs
    bucket: riff_versions
    key: <%= component.name %>-version
    json_key: ((gcp-json-key))
<% end %>

- name: cli-version
  type: semver
  source:
    initial_version: 0.0.4
    driver: gcs
    bucket: riff_versions
    key: cli-version
    json_key: ((gcp-json-key))

- name: cli-binary
  type: gcs-resource
  source:
    bucket: riff-cli-binaries
    json_key: ((gcp-json-key))
    regexp: riff-linux-amd64-*

- name: slack-alert
  type: slack-notification
  source:
    url: ((slack-hook-url))

#####################################################
# Git - Riff infra
#####################################################

<% riff_components.each do |component| %>
- name: git-<%= component.name %>
  type: git
  source:
    uri: https://github.com/<%= component.git_org_name %>/<%= component.git_repo_name %>.git
    #private_key: ((git-pfs-ci-ssh-key))
    #access_token: ((gitbot-access-token))
    branch: master

- name: github-commit-status-<%= component.name %>
  type: github-status
  source:
    repository: <%= component.git_org_name %>/<%= component.git_repo_name %>
    access_token: ((gitbot-access-token))
    context: ci/riff/<%= component.git_repo_name %>
<% end %>

- name: git-riff
  type: git
  source:
    uri: https://github.com/projectriff/riff.git
    branch: master

- name: git-riff-cli
  type: git
  source:
    uri: https://github.com/projectriff/riff-cli.git
    branch: master

- name: git-helm-charts
  type: git
  source:
    uri: https://github.com/projectriff/helm-charts.git
    branch: master

- name: github-commit-status-helm-charts
  type: github-status
  source:
    repository: projectriff/helm-charts
    access_token: ((gitbot-access-token))
    context: ci/riff/helm-charts

- name: git-kubernetes-model
  type: git
  source:
    uri: https://github.com/projectriff/kubernetes-model.git
    branch: riff

#####################################################
# Git - CI
#####################################################

- name: git-pfs-ci
  type: git
  source:
    uri: git@github.com:projectriff/ci.git
    private_key: ((git-pfs-ci-ssh-key))
    branch: master

- name: git-faas-acceptance-test-suite
  type: git
  source:
    uri: git@github.com:projectriff/fats.git
    private_key: ((git-pfs-ci-ssh-key))
    branch: master

#####################################################
# Docker images
#####################################################

<% riff_components.each do |component| %>
- name:  <%= component.name %>-docker-image
  type: docker-image
  source:
    repository: ((docker-riff-org))/<%= component.docker_image_name %>
    username: ((docker-riff-username))
    password: ((docker-riff-password))
<% end %>

#################### Sample Images ##################

## Node ##

- name:  node-sample-image
  type: docker-image
  source:
    repository: ((docker-test-org))/node-sample-image
    username: ((docker-riff-username))
    password: ((docker-riff-password))

#####################################################
# JOBS
#####################################################

jobs:

- name: build-riff-cli
  plan:
  - aggregate:
    - get: git-riff-cli
    - get: git-pfs-ci
    - get: cli-version
  - put: cli-version
    params: {pre: build}
  - task: build-riff-cli
    file: git-pfs-ci/tasks/cli/build/task.yml
  - put: cli-binary
    params:
        file: cli-output/riff-linux-amd64-*
        predefined_acl: publicRead
        content_type: application/x-executable

- name: build-node-sample-image
  plan:
  - aggregate:
    - get: git-riff
    - get: git-pfs-ci
    - get: node-function-invoker-version
      trigger: true
      passed: [build-node-function-invoker-container]
  - task: perform-init
    file: git-pfs-ci/tasks/samples/init-dockerfile/task.yml
    input_mapping:
      invoker-version: node-function-invoker-version
    params:
      SAMPLE_PATH: samples/node/square
      SAMPLE_ARTIFACT: square.js
      SAMPLE_LANGUAGE: node
      DOCKER_TEST_ORG: riffci
  - put: node-sample-image
    params:
      build: riff-init-output
      tag: node-function-invoker-version/version

<% riff_components.each do |component| %>
- name: build-<%= component.name %>-container
  serial_groups: [<%= component.name %>]
  plan:
  - aggregate:
    - get: git-pfs-ci
    - get: git-<%= component.name %>
      trigger: true
    - get: <%= component.name %>-version
<% if component.name == 'function-controller' %>
    - get: git-kubernetes-model
<% end %>

  - put: <%= component.name %>-version
    params: {pre: build}

  - put: github-commit-status-<%= component.name %>
    params:
      commit: git-<%= component.name %>
      state: pending

  - task: build-<%= component.name %>
    file: git-pfs-ci/tasks/<%= component.build_task_file %>
    on_failure:
      put: github-commit-status-<%= component.name %>
      params:
        commit: git-<%= component.name %>
        state: failure

  - put: <%= component.name %>-docker-image
    params:
      build: docker-context
      tag: docker-context/docker_version
      tag_as_latest: true
    <% if component.name == 'function-controller' %>
      build_args:
        JAR_FILE: "*.jar"
    <% end %>

  on_success:
    put: github-commit-status-<%= component.name %>
    params:
      commit: git-<%= component.name %>
      state: success

<%= slack_notification %>
<% end %>

######################################################
# helm charts
######################################################

- name: build-riff-chart
  serial_groups: [riff]
  plan:
  - aggregate:
    - get: git-pfs-ci
    - get: git-helm-charts
  <% riff_components.each do |component| %>
    - get: <%= component.name %>-version
      passed:
      - build-<%= component.name %>-container
  <% end %>
  <% riff_components.each do |component| %>
    - get: git-<%= component.name %>
      trigger: true
      passed: [build-<%= component.name %>-container]
      params:
        depth: 1
  <% end %>
  - put: github-commit-status-helm-charts
    params:
      commit: git-helm-charts
      state: pending
  - task: build-riff-chart
    file: git-pfs-ci/tasks/helm-charts/build/task.yml
    params:
      HELM_CHARTS_URL: "https://<%= charts_bucket_name %>.storage.googleapis.com"
    on_failure:
      put: github-commit-status-helm-charts
      params:
        commit: git-helm-charts
        state: failure
  - put: gcs-riff-chart-latest-version
    params:
      file: helm-charts-latest-version/latest_version
      predefined_acl: publicRead
  - put: gcs-riff-chart-latest-name
    params:
      file: helm-charts-latest-name/latest_name
      predefined_acl: publicRead
  - put: gcs-riff-charts
    params:
      file: helm-charts/*.tgz
      predefined_acl: publicRead
  - put: gcs-riff-charts
    params:
      file: helm-charts-install/*
      predefined_acl: publicRead
  - put: gcs-riff-chart-index
    params:
      file: helm-charts/index.yaml
      predefined_acl: publicRead
  on_success:
    put: github-commit-status-helm-charts
    params:
      commit: git-helm-charts
      state: success
<%= slack_notification %>

<% k8s_envs.each do |k8s_env| %>
- name: clean-riff-pre-deploy-<%= k8s_env.name %>
  serial_groups: [riff-<%= k8s_env.name %>]
  plan:
  - aggregate:
    - get: gcs-riff-chart-latest-version
      passed: [build-riff-chart]
    - get: gcs-riff-chart-latest-name
      passed: [build-riff-chart]
    - get: git-pfs-ci
  <% riff_components.each do |component| %>
    - get: <%= component.name %>-version
      passed: [build-riff-chart]
  <% end %>
    - get: gcs-riff-chart-index
      passed: [build-riff-chart]
      trigger: true

  - task: clean-riff-deployment
    file: git-pfs-ci/tasks/riff-deployment/clean/task.yml
    params:
      KUBECONFIG_STRING: ((<%= k8s_env.lpass_name %>))
      KUBECONFIG_CERT: ((<%= k8s_env.lpass_name %>-crt))
      KUBECONFIG_KEY: ((<%= k8s_env.lpass_name %>-key))
<%= slack_notification %>

- name: deploy-riff-<%= k8s_env.name %>
  serial_groups: [riff-<%= k8s_env.name %>]
  plan:
  - aggregate:
    - get: gcs-riff-chart-latest-version
      passed: [clean-riff-pre-deploy-<%= k8s_env.name %>]
    - get: gcs-riff-chart-latest-name
      passed: [clean-riff-pre-deploy-<%= k8s_env.name %>]
    - get: git-pfs-ci
  <% riff_components.each do |component| %>
    - get: <%= component.name %>-version
      passed: [clean-riff-pre-deploy-<%= k8s_env.name %>]
  <% end %>
    - get: gcs-riff-chart-index
      passed: [clean-riff-pre-deploy-<%= k8s_env.name %>]
      trigger: true

  - task: deploy-riff
    file: git-pfs-ci/tasks/riff-deployment/deploy/task.yml
    params:
      KUBECONFIG_STRING: ((<%= k8s_env.lpass_name %>))
      KUBECONFIG_CERT: ((<%= k8s_env.lpass_name %>-crt))
      KUBECONFIG_KEY: ((<%= k8s_env.lpass_name %>-key))
      HELM_CHARTS_URL: "https://<%= charts_bucket_name %>.storage.googleapis.com"
<%= slack_notification %>

- name: run-faas-acceptance-tests-<%= k8s_env.name %>
  serial_groups: [riff-<%= k8s_env.name %>]
  plan:
  - aggregate:
    - get: git-riff
    - get: git-riff-cli
    - get: gcs-riff-chart-latest-version
      passed: [deploy-riff-<%= k8s_env.name %>]
    - get: gcs-riff-chart-latest-name
      passed: [deploy-riff-<%= k8s_env.name %>]
    - get: git-pfs-ci
  <% riff_components.each do |component| %>
    - get: <%= component.name %>-version
      passed: [deploy-riff-<%= k8s_env.name %>]
  <% end %>
    - get: gcs-riff-chart-index
      passed: [deploy-riff-<%= k8s_env.name %>]
      trigger: true
    - get: git-faas-acceptance-test-suite

  - task: run-riff-system-tests
    privileged: true
    file: git-pfs-ci/tasks/acceptance-tests/task.yml
    params:
      GINKGO_FOCUS: node
      KUBECONFIG_STRING: ((<%= k8s_env.lpass_name %>))
      KUBECONFIG_CERT: ((<%= k8s_env.lpass_name %>-crt))
      KUBECONFIG_KEY: ((<%= k8s_env.lpass_name %>-key))
      DOCKER_TEST_ORG: ((docker-test-org))
      DOCKER_USERNAME: ((docker-riff-username))
      DOCKER_PASSWORD: ((docker-riff-password))
<%= slack_notification %>

- name: clean-riff-post-deploy-<%= k8s_env.name %>
  serial_groups: [riff-<%= k8s_env.name %>]
  plan:
  - aggregate:
    - get: gcs-riff-chart-latest-version
      passed: [run-faas-acceptance-tests-<%= k8s_env.name %>]
    - get: gcs-riff-chart-latest-name
      passed: [run-faas-acceptance-tests-<%= k8s_env.name %>]
    - get: git-pfs-ci
  <% riff_components.each do |component| %>
    - get: <%= component.name %>-version
      passed: [run-faas-acceptance-tests-<%= k8s_env.name %>]
  <% end %>
    - get: gcs-riff-chart-index
      passed: [run-faas-acceptance-tests-<%= k8s_env.name %>]
      trigger: true

  - task: clean-riff-deployment
    file: git-pfs-ci/tasks/riff-deployment/clean/task.yml
    params:
      KUBECONFIG_STRING: ((<%= k8s_env.lpass_name %>))
      KUBECONFIG_CERT: ((<%= k8s_env.lpass_name %>-crt))
      KUBECONFIG_KEY: ((<%= k8s_env.lpass_name %>-key))<%= slack_notification %>
<%= slack_notification %>
<% end %>

- name: manual-publish-crds
  plan:
  - aggregate:
    - get: git-pfs-ci
    - get: git-helm-charts

<% k8s_envs.each do |k8s_env| %>
  - task: publish-crds-<%= k8s_env.name %>
    file: git-pfs-ci/tasks/custom-resource-definitions/publish/task.yml
    params:
      KUBECONFIG_STRING: ((<%= k8s_env.lpass_name %>))
      KUBECONFIG_CERT: ((<%= k8s_env.lpass_name %>-crt))
      KUBECONFIG_KEY: ((<%= k8s_env.lpass_name %>-key))
<% end %>
<%= slack_notification %>

- name: manual-images-version-bump-build
  plan:
  <% riff_components.each do |component| %>
  - put: <%= component.name %>-version
    params: {pre: build}
  <% end %>
<%= slack_notification %>

- name: manual-images-version-bump-patch
  plan:
  <% riff_components.each do |component| %>
  - put: <%= component.name %>-version
    params: {bump: patch, pre: build}
  <% end %>
<%= slack_notification %>

- name: manual-images-release
  plan:
  - get: git-pfs-ci
<% riff_components.each do |component| %>
  - get: <%= component.name %>-version
    passed:
    - build-<%= component.name %>-container
<% end %>
<% riff_components.each do |component| %>
  - task: release-<%= component.name %>
    file: git-pfs-ci/tasks/release-management/docker-image-tagging/task.yml
    input_mapping: { source-semver: <%= component.name %>-version }
    privileged: true
    params:
      DOCKERHUB_ORG_SOURCE: ((docker-riff-org))
      DOCKERHUB_ORG_TARGET: ((docker-riff-org))
      DOCKERHUB_USERNAME: ((docker-riff-username))
      DOCKERHUB_PASSWORD: ((docker-riff-password))
      DOCKER_IMAGE: <%= component.docker_image_name %>
<% end %>
<%= slack_notification %>
